### ISSUE TITLE
Handle of setExtremes after reset zoom event

### ISSUE THREAD

**Issue by pghilardi** [gevgeny/highcharts-flags-grouping#1]
I am facing some problems after the trigger of the reset zoom action. This action set the extremes with min and max as undefined and the plug-in does not handle this case.

I think that the following code should be added on the setExtremes wrap:

```
if (min == undefined && max == undefined){
  min = axis.getExtremes().dataMin
  max = axis.getExtremes().dataMax
  timeSpan = max - min;
}
```

What do you think?

**Comment by gevgeny** [comment]
@pghilardi Done. Plz check and let me know if it works as aspected so i can update version.

**Comment by pghilardi** [comment]
@gevgeny, Thanks! It worked! :)

**Comment by gevgeny** [comment]
Thanks for the issue request. Feel free to post more ;)
