### ISSUE TITLE
Is this plugin still working in 2022 with HS10.x?

### ISSUE THREAD

**Issue by Organizer21** [gevgeny/highcharts-flags-grouping#3]
Just came across this and I was thinking that there's no way the official solution is not offering something like this as it makes absolute sense to have some sort of grouping if you got a big timeline with flags. Though unless I am wrong, it seems HS still does not support this after six years ?! About to update HS from to 7x to 10.x and after that I'll be looking at this, does this plugin still work?

**Comment by gevgeny** [comment]
@Organizer21 wow, I did not expect it may be still interesting, I have not been supporting it for years. You can check it and PR, then I will merge it  :)
